export const CUSTOMER_TAB = {
  id: 'ID',
  created_at: 'Vytvořeno',
  updated_at: 'Poslední změna',
  name: 'Jméno',
  ico: 'IČO',
  products_count: 'Počet produktů',
  purchases_count: 'Počet nákupů',
  is_archived: 'Archivováno',
}

export const TRADERS_TAB = {
  id: 'ID',
  created_at: 'Vytvořeno',
  updated_at: 'Poslední změna',
  subject_name: 'Jméno',
  license_num: 'Číslo Licence',
  is_archived: 'Archivováno',
  is_active: 'Aktivní',
}

export const PRODUCTS_TAB = {
  id: 'ID',
  created_at: 'Vytvořeno',
  updated_at: 'Poslední změna',
  ico: 'IČO',
  year: 'Rok',
  pc: 'Produkt CAL',
  pq: 'Produkt Q',
  pm: 'Produkt M',
  ps: 'Produkt SPOT',
  pc_ratio: 'Produkt CAL poměr',
  pq_ratio: 'Produkt Q poměr',
  pm_ratio: 'Produkt M poměr',
  ps_ratio: 'Produkt SPOT poměr',
  tamnt: 'Celkové množství',
  purgastype: 'Typ nakupu zemniho plynu',
  note: 'Poznámka',
  trader: 'Obchodník s plynem',
  tolerance: 'Tolerance',
  customer_id: 'Zákazník ID',
  trader_id: 'Obchodník s plynem ID',
  is_archived: 'Archivováno',
}

export const PURCHASES_TAB = {
  id: 'ID',
  created_at: 'Vytvořeno',
  updated_at: 'Poslední změna',
  ico: 'IČO',
  year: 'Rok',
  currency: 'Měna',
  pcq: 'Produkt CAL množství',
  pcp: 'Produkt CAL cena',
  pq1q: 'Produkt Q1 množství',
  pq1p: 'Produkt Q1 cena',
  pq2q: 'Produkt Q2 množství',
  pq2p: 'Produkt Q2 cena',
  pq3q: 'Produkt Q3 množství',
  pq3p: 'Produkt Q3 cena',
  pq4q: 'Produkt Q4 množství',
  pq4p: 'Produkt Q4 cena',
  pm1q: 'Produkt M1 množství',
  pm1p: 'Produkt M1 cena',
  pm2q: 'Produkt M2 množství',
  pm2p: 'Produkt M2 cena',
  pm3q: 'Produkt M3 množství',
  pm3p: 'Produkt M3 cena',
  pm4q: 'Produkt M4 množství',
  pm4p: 'Produkt M4 cena',
  pm5q: 'Produkt M5 množství',
  pm5p: 'Produkt M5 cena',
  pm6q: 'Produkt M6 množství',
  pm6p: 'Produkt M6 cena',
  pm7q: 'Produkt M7 množství',
  pm7p: 'Produkt M7 cena',
  pm8q: 'Produkt M8 množství',
  pm8p: 'Produkt M8 cena',
  pm9q: 'Produkt M9 množství',
  pm9p: 'Produkt M9 cena',
  pm10q: 'Produkt M10 množství',
  pm10p: 'Produkt M10 cena',
  pm11q: 'Produkt M11 množství',
  pm11p: 'Produkt M11 cena',
  pm12q: 'Produkt M12 množství',
  pm12p: 'Produkt M12 cena',
  note: 'Poznámka',
  cal_pur_date: 'Produkt CAL datum nákupu',
  q1_pur_date: 'Produkt Q1 datum nákupu',
  q2_pur_date: 'Produkt Q2 datum nákupu',
  q3_pur_date: 'Produkt Q3 datum nákupu',
  q4_pur_date: 'Produkt Q4 datum nákupu',
  m1_pur_date: 'Produkt M1 datum nákupu',
  m2_pur_date: 'Produkt M2 datum nákupu',
  m3_pur_date: 'Produkt M3 datum nákupu',
  m4_pur_date: 'Produkt M4 datum nákupu',
  m5_pur_date: 'Produkt M5 datum nákupu',
  m6_pur_date: 'Produkt M6 datum nákupu',
  m7_pur_date: 'Produkt M7 datum nákupu',
  m8_pur_date: 'Produkt M8 datum nákupu',
  m9_pur_date: 'Produkt M9 datum nákupu',
  m10_pur_date: 'Produkt M10 datum nákupu',
  m11_pur_date: 'Produkt M11 datum nákupu',
  m12_pur_date: 'Produkt M12 datum nákupu',
  spot_m1: 'Spotové vyrovnání M1',
  spot_m2: 'Spotové vyrovnání M2',
  spot_m3: 'Spotové vyrovnání M3',
  spot_m4: 'Spotové vyrovnání M4',
  spot_m5: 'Spotové vyrovnání M5',
  spot_m6: 'Spotové vyrovnání M6',
  spot_m7: 'Spotové vyrovnání M7',
  spot_m8: 'Spotové vyrovnání M8',
  spot_m9: 'Spotové vyrovnání M9',
  spot_m10: 'Spotové vyrovnání M10',
  spot_m11: 'Spotové vyrovnání M11',
  spot_m12: 'Spotové vyrovnání M12',
  spot_m1_value: 'Spotové vyrovnání M1 hodnota',
  spot_m2_value: 'Spotové vyrovnání M2 hodnota',
  spot_m3_value: 'Spotové vyrovnání M3 hodnota',
  spot_m4_value: 'Spotové vyrovnání M4 hodnota',
  spot_m5_value: 'Spotové vyrovnání M5 hodnota',
  spot_m6_value: 'Spotové vyrovnání M6 hodnota',
  spot_m7_value: 'Spotové vyrovnání M7 hodnota',
  spot_m8_value: 'Spotové vyrovnání M8 hodnota',
  spot_m9_value: 'Spotové vyrovnání M9 hodnota',
  spot_m10: 'Spotové vyrovnání M10 hodnota',
  spot_m11: 'Spotové vyrovnání M11 hodnota',
  spot_m12: 'Spotové vyrovnání M12 hodnota',
  customer_id: 'Zákazník',
  is_archived: 'Archivováno',
}

