import Head from 'next/head'

export default function Home() {



    return (
        <div className="">
            <Head>
                <title>Energo Plyn | Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <section className="box">
                <h1>
                    Už ti bylo smutno Mrdko?
                </h1>
            </section>
            <section>
              Něco
            </section>
        </div>
    )
}
